In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
import pydot
from matplotlib import pyplot as plt
from keras import Input, Model, layers, Sequential

Using TensorFlow backend.


In [2]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
y = [[10, 20, 30, 40, 50]]
print(x)
print(y)
print(x.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[10, 20, 30, 40, 50]]
(5, 3)


In [5]:
tf.InteractiveSession()
Model = Sequential(name='Multi_Linear_Regression')
Model.add(layers.Dense(1, input_shape=(3,), activation='linear'))
Model.add(layers.Dense(1, activation='linear'))
Model.compile(optimizer='Adam', loss='mean_squared_error', metrics=['accuracy'])
Model.summary()

Model: "Multi_Linear_Regression"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 1)                 4         
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 2         
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________


In [6]:
Model.fit(x, y, epochs=10)

W0922 13:29:19.793442 139887830484800 deprecation_wrapper.py:119] From /home/nandagopal/PycharmProjects/data-science-class/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

W0922 13:29:19.848034 139887830484800 deprecation_wrapper.py:119] From /home/nandagopal/PycharmProjects/data-science-class/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1020: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Epoch 1/10
5/5 [==============================] - 0s 21ms/step - loss: 649.1369 - acc: 0.0000e+00
Epoch 2/10
5/5 [==============================] - 0s 271us/step - loss: 647.1070 - acc: 0.0000e+00
Epoch 3/10
5/5 [==============================] - 0s 342us/step - loss: 645.0776 - acc: 0.0000e+00
Epoch 4/10
5/5 [==============================] - 0s 265us/step - loss: 643.0485 - acc: 0.0000e+00
Epoch 5/10
5/5 [==============================] - 0s 458us/step - loss: 641.0199 - acc: 0.0000e+00
Epoch 6/10
5/5 [==============================] - 0s 433us/step - loss: 638.9915 - acc: 0.0000e+00
Epoch 7/10
5/5 [==============================] - 0s 273us/step - loss: 637.0248 - acc: 0.0000e+00
Epoch 8/10
5/5 [==============================] - 0s 320us/step - loss: 634.9973 - acc: 0.0000e+00
Epoch 9/10
5/5 [==============================] - 0s 324us/step - loss: 632.9703 - acc: 0.0000e+00
Epoch 10/10
5/5 [==============================] - 0s 374us/step - loss: 630.9437 - acc: 0.0000e+00


In [ ]:
Model.get_weights()