In [1]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
pd.options.display.float_format = '{:, .2f}'.format
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [2]:
f1 = '''head
body
facset_start
fact1
fact1
end_square
tail'''

In [3]:
f2 = '''head
body
body
facset_start
fact1
fact1
end_square
tail'''

In [4]:
f3 = '''head
body
body
facset_start
fact1
container
textbox
column
fact1
end_square
tail'''

In [5]:
# count_vectorizer = CountVectorizer(stop_words='english')
count_vectorizer = CountVectorizer()


sp = count_vectorizer.fit_transform([f1, f2, f3])


In [6]:
sp

<3x9 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [30]:
print(count_vectorizer.get_feature_names())
print(sp.todense())

['body', 'column', 'container', 'end_square', 'facset_start', 'fact1', 'head', 'tail', 'textbox']
[[1 0 0 1 1 2 1 1 0]
 [2 0 0 1 1 2 1 1 0]
 [2 1 1 1 1 2 1 1 1]]


In [31]:
df = pd.DataFrame(sp.todense(), 
                  columns=count_vectorizer.get_feature_names(), 
                  index=['f1', 'f2', 'f3'])

In [32]:
df

body  column  container  end_square  facset_start  fact1  head  tail  \
f1     1       0          0           1             1      2     1     1   
f2     2       0          0           1             1      2     1     1   
f3     2       1          1           1             1      2     1     1   

    textbox  
f1        0  
f2        0  
f3        1

In [33]:
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df))

[[1.000 0.962 0.861]
 [0.962 1.000 0.894]
 [0.861 0.894 1.000]]


In [24]:
from nltk.translate.bleu_score import sentence_bleu, corpus_bleu

from nltk.translate.bleu_score import SmoothingFunction
chencherry = SmoothingFunction()

In [25]:
reference = [f1.split('\n')]
candidate = f2.split('\n')
score = sentence_bleu(reference, candidate, weights=(1, 0, 0, 0), smoothing_function=chencherry.method2)

score

0.8888888888888888

In [39]:
reference = [['i', 'am', 'here', 'today', 'for', 'work'], 
            ['i', 'am', 'here', 'today', 'to', 'work']]
candidate = ['i', 'am', 'here', 'today','for', 'work', 'and', 'fun']

# reference = [['the', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']]
# candidate = ['the', 'brown', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']
score = sentence_bleu(reference, candidate, weights=(0,0,1,0), smoothing_function=chencherry.method2)
score

0.7142857142857143

In [27]:
2/8

0.25