## Numpy and Matrix Implementations

In [13]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=3)

Matrix --> numbers arraged in rectangular row and column wise
Vector --> Matrix with 1 column --> has magnitude and direction

Euclidean Space

    -Space, in mathematics, is a collection of geometrical points
    -Euclidean Space - Joining two points will be always straight 

Matrix Properties

    -Not Cummutative
    -Associative 


In [2]:
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3)

In [3]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
A + B 

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [6]:
A - B

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
np.dot(A, B)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

## LinearAlgebra

In [14]:
X = np.random.random_sample((2,2)) * 100

In [15]:
X

array([[92.829,  4.316],
       [43.166, 31.02 ]])

In [16]:
Y = np.random.random_sample((2,)) * 100

In [17]:
Y

array([53.339, 49.511])

In [18]:
np.linalg.solve(X, Y)

array([0.535, 0.852])

Links [https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html]