In [1]:
# pip install numpy 
import numpy as np

# nandagopal@IMCHLT094:~$ pip3 install numpy
# Collecting numpy
#   Cache entry deserialization failed, entry ignored
#   Downloading https://files.pythonhosted.org/packages/e5/e6/c3fdc53aed9fa19d6ff3abf97dfad768ae3afce1b7431f7500000816bda5/numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl (20.4MB)
#     100% |████████████████████████████████| 20.4MB 77kB/s 
# Installing collected packages: numpy
# Successfully installed numpy-1.17.2


List = [1122,2,3]

In [2]:
np.array(object=List)

array([1122,    2,    3])

In [3]:
np.array(object=List, dtype=int)

array([1122,    2,    3])

In [4]:
np.array(object=List, dtype=float)

array([1122.,    2.,    3.])

In [5]:
np.array(object=List, dtype='S2')

array([b'11', b'2', b'3'], dtype='|S2')

In [6]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
arr.ndim

1

In [8]:
arr.item

<function ndarray.item>

In [9]:
arr.itemsize

8

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
arr.shape


(20,)

In [12]:
arr.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
n_arr = arr.reshape(4,5)

In [15]:
n_arr.shape

(4, 5)

In [16]:
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
arr.ndim

1

In [18]:
n_arr.ndim

2

In [19]:
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
n_arr[..., 2]

array([ 2,  7, 12, 17])

In [21]:
n_arr[2]

array([10, 11, 12, 13, 14])

In [22]:
n_arr[...,0]

array([ 0,  5, 10, 15])

In [23]:
mul = np.array([0, 0 , 0, 0, 0])

In [24]:
n_arr * mul

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
n_arr + mul

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
mul * 5

array([0, 0, 0, 0, 0])

In [27]:
mul + 5

array([5, 5, 5, 5, 5])

In [28]:
mul + np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [29]:
for i in np.nditer(n_arr):
    print(i, type(i))

0 <class 'numpy.ndarray'>
1 <class 'numpy.ndarray'>
2 <class 'numpy.ndarray'>
3 <class 'numpy.ndarray'>
4 <class 'numpy.ndarray'>
5 <class 'numpy.ndarray'>
6 <class 'numpy.ndarray'>
7 <class 'numpy.ndarray'>
8 <class 'numpy.ndarray'>
9 <class 'numpy.ndarray'>
10 <class 'numpy.ndarray'>
11 <class 'numpy.ndarray'>
12 <class 'numpy.ndarray'>
13 <class 'numpy.ndarray'>
14 <class 'numpy.ndarray'>
15 <class 'numpy.ndarray'>
16 <class 'numpy.ndarray'>
17 <class 'numpy.ndarray'>
18 <class 'numpy.ndarray'>
19 <class 'numpy.ndarray'>


In [30]:
arr, arr.T

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]))

In [31]:
arr.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
n_arr.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [51]:
np.transpose(n_arr.T)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
for i in n_arr.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [34]:
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
np.amin(n_arr)

0

In [36]:
np.amax(n_arr)

19

In [37]:
np.amin(n_arr, 1)


array([ 0,  5, 10, 15])

In [38]:
np.median(n_arr, 1)

array([ 2.,  7., 12., 17.])

In [39]:
np.mean(n_arr)

9.5

In [40]:
n_arr.shape

(4, 5)

In [41]:
np.var(n_arr[0])


2.0

In [42]:
np.std(n_arr[0])

1.4142135623730951

In [43]:
X = np.array([[5,3],  
     [10,15],
     [15,12],
     [24,10],
     [30,45],
     [85,70],
     [71,80],
     [60,78],
     [55,52],
     [80,91],])

In [44]:
X

array([[ 5,  3],
       [10, 15],
       [15, 12],
       [24, 10],
       [30, 45],
       [85, 70],
       [71, 80],
       [60, 78],
       [55, 52],
       [80, 91]])

In [45]:
np.append(X , np.random.randint(len(X), size=(10,1)), axis=1)

array([[ 5,  3,  7],
       [10, 15,  8],
       [15, 12,  4],
       [24, 10,  9],
       [30, 45,  9],
       [85, 70,  9],
       [71, 80,  6],
       [60, 78,  8],
       [55, 52,  8],
       [80, 91,  4]])

In [46]:
np.rand(len(X))

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.randint(10, size=(10,))

In [ ]:
from sklearn.cluster import KMeans
import matplotlib.pylab as plt
%matplotlib inline

In [ ]:
X_X = np.append(X , np.random.randint(100, size=(10,1)), axis=1)
plt.scatter(X_X[:,0],X_X[:,2], label='True Position')  

In [ ]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(X_X)

In [ ]:
kmeans.labels_

In [ ]:
plt.scatter(X_X[:,0],X_X[:,1], label='True Position', c=kmeans.labels_)  

In [ ]:
plt.scatter(X_X[:,0],X_X[:,1], label='True Position', c=kmeans.labels_)  

In [ ]:
import numpy as np 
a = np.array([1,2,3,4,5]) 
np.save('outfile',a)

In [ ]:
a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 


In [ ]:
b = np.loadtxt('out.txt') 
print(b)

In [ ]:
import numpy.matlib 
import numpy as np 

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

In [ ]:
np.matmul(a, b)

In [ ]:
np.vdot(a,b)

In [ ]:
a = np.array([1,2,3])

In [ ]:
id(a)

In [ ]:
b = a

In [ ]:
id(b)

In [ ]:
np.append(b, [4,5,6])

In [ ]:
id(a)

In [ ]:
id(b)

In [ ]:
a

In [ ]:
b

In [ ]:
a == b

In [ ]:
b

In [ ]:
b = np.append(b, [4,5,6])

In [ ]:
id(b)

In [ ]:
a == b

In [ ]:
a is b

In [ ]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 'd', 'e'])

In [ ]:
frame

In [ ]:
print (frame['a'].corr(frame['e']))