In [1]:
import numpy as np

# np.c_ slice objects to concatenation along the second axis.

In [14]:
x = np.array([1,2,3,4])
y = np.array([4,5,6,7])

print(x.shape)
print(y.shape)

(4,)
(4,)


np.c_ concatinate the 2 arrays of shape m*n and m*b into single array of shape m*(n+b) , i.e it adds along the 2nd axis 

In [15]:
np.c_[x, y]

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [9]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

print(x.shape)
print(y.shape)

(1, 3)
(1, 3)


In [8]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [17]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])

print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


In [18]:
np.c_[x, y].

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])