In [1]:
from sklearn.datasets.samples_generator import make_blobs

In [2]:
num_of_features = 3
number_of_clusters = 3 
X, y = make_blobs(n_samples=10,n_features=num_of_features, centers=num_of_features)

In [3]:
type(X)

numpy.ndarray

In [4]:
X.shape

(10, 3)

# Slicing only the Columns

In [5]:
X[...,1]

array([ 0.61604379, -1.44471036,  1.47398179,  0.47704911,  0.09701941,
       -1.00361308, -0.42482375,  0.7808825 , -1.10010137,  2.05438229])

In [6]:
X[...,2]

array([ 8.7252303 ,  7.14117998, -2.20605032, -1.871733  , -3.71211657,
       -0.70656356,  6.67800278, -0.94894305,  8.22995845, -3.48471772])

In [8]:
X[...,0]

array([ 10.17466979,  10.03055572, -11.19884234, -10.45734228,
        -6.8808439 ,  -8.9155297 ,  10.4260207 ,  -7.10547246,
         9.79548415, -10.02685964])