In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Formatting...
float_formatter = lambda x: "%.4f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})


#Sklearn 
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression

scaler = StandardScaler()
normalizer = MinMaxScaler()

# Observations: 

In [38]:
limit = 6 + 1
x1 = np.array([x for x in range(1, limit)], ndmin=1).reshape(-1,1)
x2 = 2*x1

x2=x2.reshape(-1, 1)

print(x1)
print(x2)
# print(x1.reshape(2, 3))

np.append(x1, x2).reshape(6,2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 2,  4],
       [ 6,  8],
       [10, 12]])

In [39]:
X = np.stack((x1, x2), axis=1)
X

array([[[ 1],
        [ 2]],

       [[ 2],
        [ 4]],

       [[ 3],
        [ 6]],

       [[ 4],
        [ 8]],

       [[ 5],
        [10]],

       [[ 6],
        [12]]])

In [40]:
X.shape

(6, 2, 1)